### ISSUE TITLE
The 'jaeger_browser' distribution was not found - is this an issue?

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci-datascience-installer#4]
Launching JupyterLab, I get the following error, but JupyterLab still seems to launch fine. I remember that Jaeger is something @saulshanabrook was using for the ibis-vega-transform.

```bash
(omnisci) dharhas@dharhas-mbp ~ $ jupyter lab                                                                                                                                  
[W 08:00:11.380 LabApp] Error loading server extension jupyter_server_proxy
    Traceback (most recent call last):
      File "/Users/dharhas/omnitest5/omnisci/lib/python3.7/site-packages/notebook/notebookapp.py", line 1945, in init_server_extensions
        func(self)
      File "/Users/dharhas/omnitest5/omnisci/lib/python3.7/site-packages/jupyter_server_proxy/__init__.py", line 27, in load_jupyter_server_extension
        server_processes += get_entrypoint_server_processes()
      File "/Users/dharhas/omnitest5/omnisci/lib/python3.7/site-packages/jupyter_server_proxy/config.py", line 75, in get_entrypoint_server_processes
        make_server_process(entry_point.name, entry_point.load()())
      File "/Users/dharhas/omnitest5/omnisci/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2471, in load
        self.require(*args, **kwargs)
      File "/Users/dharhas/omnitest5/omnisci/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2494, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/Users/dharhas/omnitest5/omnisci/lib/python3.7/site-packages/pkg_resources/__init__.py", line 785, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'jaeger_browser' distribution was not found and is required by the application
```

**Comment by xmnlab** [comment]
jupyter-jaeger now is packaged using jupyter-package and jaeger-browser is explicitly defined as a dependency here https://github.com/Quansight/omnisci-datascience-installer/blob/master/constructor/environment.yaml#L17
